export const data = [
    {
      name: "Contract XYZ",
      status: "Review",
      statusColor: "blue-500",
      assigned: ["AJ"],
      unassigned: ["JS"],
      uploaded: "1 min ago",
      activity: "New Version Generated",
      updated: "7 min ago",
    },
    {
      name: "Contract XYZ",
      status: "Review",
      statusColor: "blue-500",
      assigned: ["AJ"],
      unassigned: ["JS"],
      uploaded: "1 min ago",
      activity: "New Version Generated",
      updated: "7 min ago",
    },
    {
      name: "Contract XYZ",
      status: "Signature",
      statusColor: "yellow-500",
      assigned: ["AJ"],
      unassigned: ["JS"],
      uploaded: "3 days ago",
      activity: "Sent for Signature",
      updated: "10 min ago",
    },
    {
      name: "Contract XYZ",
      status: "Signature",
      statusColor: "yellow-500",
      assigned: [],
      unassigned: ["JS"],
      uploaded: "3 days ago",
      activity: "Sent for Signature",
      updated: "10 min ago",
    },
    {
      name: "Contract XYZ",
      status: "Signature",
      statusColor: "yellow-500",
      assigned: ["AJ"],
      unassigned: [],
      uploaded: "3 days ago",
      activity: "Sent for Signature",
      updated: "10 min ago",
    },
    {
      name: "Contract XYZ",
      status: "Signature",
      statusColor: "yellow-500",
      assigned: ["AJ"],
      unassigned: ["JS"],
      uploaded: "3 days ago",
      activity: "Sent for Signature",
      updated: "10 min ago",
    },
  ];